### ISSUE TITLE
项目刚检出，运行报错 （sdk 4.2.2） target=17

### ISSUE THREAD

**Issue by frank0417** [eoecn/android-app#78]
06-12 22:38:36.169: E/dalvikvm(12962): Could not find class 'cn.eoe.app.ui.MainActivity', referenced from method cn.eoe.app.ui.SplashActivity.goHome
06-12 22:38:36.179: E/AndroidRuntime(12962): FATAL EXCEPTION: main
06-12 22:38:36.179: E/AndroidRuntime(12962): java.lang.NoClassDefFoundError: com.umeng.analytics.MobclickAgent
06-12 22:38:36.179: E/AndroidRuntime(12962):    at cn.eoe.app.ui.base.BaseActivity.onCreate(BaseActivity.java:36)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at cn.eoe.app.ui.SplashActivity.onCreate(SplashActivity.java:21)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at android.app.ActivityThread.access$1500(ActivityThread.java:117)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at android.os.Looper.loop(Looper.java:130)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at android.app.ActivityThread.main(ActivityThread.java:3683)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at java.lang.reflect.Method.invokeNative(Native Method)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at java.lang.reflect.Method.invoke(Method.java:507)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664)
06-12 22:38:36.179: E/AndroidRuntime(12962):    at dalvik.system.NativeStart.main(Native Method)

**Comment by frank0417** [comment]
有没有人遇到此问题？

**Comment by IceskYsl** [comment]
是elicpse？

**Comment by frank0417** [comment]
google 官方adt,已经找到原因了，发布时jar没打进去

**Comment by kesco** [comment]
请问是哪个JAR没打进去，我也遇到同样的问题。

**Comment by frank0417** [comment]
umeng_sdk.jar

**Comment by vinceyuan** [comment]
我手动加入了umeng_sdk.jar，但是依然有这个问题。 Could not find class 'cn.eoe.app.ui.MainActivity', referenced from method cn.eoe.app.ui.SplashActivity.goHome 无论是在真实设备还是在虚拟机上都有。

我在mac上用eclipse。

**Comment by frank0417** [comment]
在项目的java buid path 中，将order and export中的libraries都选中，然后重新编译一下

**Comment by vinceyuan** [comment]
果然如此。多谢 frank0417

其他project都没有这个要求

**Comment by mjkohoh** [comment]
不顺便关了这个issue @IceskYsl 。原谅我的强迫症

**Comment by mjkohoh** [comment]
要不顺便关了这个issue @IceskYsl 。原谅我的强迫症
