### ISSUE TITLE
运行报NoClassDefFoundError

### ISSUE THREAD

**Issue by caoyi01** [eoecn/android-app#79]
06-21 10:17:11.098: E/AndroidRuntime(367): FATAL EXCEPTION: main
06-21 10:17:11.098: E/AndroidRuntime(367): java.lang.NoClassDefFoundError: com.umeng.analytics.MobclickAgent
06-21 10:17:11.098: E/AndroidRuntime(367):  at cn.eoe.app.ui.base.BaseActivity.onCreate(BaseActivity.java:36)
06-21 10:17:11.098: E/AndroidRuntime(367):  at cn.eoe.app.ui.SplashActivity.onCreate(SplashActivity.java:21)
06-21 10:17:11.098: E/AndroidRuntime(367):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
06-21 10:17:11.098: E/AndroidRuntime(367):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
06-21 10:17:11.098: E/AndroidRuntime(367):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
06-21 10:17:11.098: E/AndroidRuntime(367):  at android.app.ActivityThread.access$2300(ActivityThread.java:125)
06-21 10:17:11.098: E/AndroidRuntime(367):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
06-21 10:17:11.098: E/AndroidRuntime(367):  at android.os.Handler.dispatchMessage(Handler.java:99)
06-21 10:17:11.098: E/AndroidRuntime(367):  at android.os.Looper.loop(Looper.java:123)
06-21 10:17:11.098: E/AndroidRuntime(367):  at android.app.ActivityThread.main(ActivityThread.java:4627)
06-21 10:17:11.098: E/AndroidRuntime(367):  at java.lang.reflect.Method.invokeNative(Native Method)
06-21 10:17:11.098: E/AndroidRuntime(367):  at java.lang.reflect.Method.invoke(Method.java:521)
06-21 10:17:11.098: E/AndroidRuntime(367):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
06-21 10:17:11.098: E/AndroidRuntime(367):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
06-21 10:17:11.098: E/AndroidRuntime(367):  at dalvik.system.NativeStart.main(Native Method)

手动导入umeng包，再运行还是报这个错误，怎么解决？？
现在只要调用umeng包就报这个错误，我该怎么解决？

**Comment by KennethYo** [comment]
build path不能解决的话，试着把我截图里的东西都勾选上。

youzicong

发件人： caoyi01
发送时间： 2013-06-21 10:11
收件人： eoecn/android-app
主题： [android-app] 运行报NoClassDefFoundError (#79)
06-21 10:17:11.098: E/AndroidRuntime(367): FATAL EXCEPTION: main
06-21 10:17:11.098: E/AndroidRuntime(367): java.lang.NoClassDefFoundError: com.umeng.analytics.MobclickAgent
06-21 10:17:11.098: E/AndroidRuntime(367): at cn.eoe.app.ui.base.BaseActivity.onCreate(BaseActivity.java:36)
06-21 10:17:11.098: E/AndroidRuntime(367): at cn.eoe.app.ui.SplashActivity.onCreate(SplashActivity.java:21)
06-21 10:17:11.098: E/AndroidRuntime(367): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
06-21 10:17:11.098: E/AndroidRuntime(367): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
06-21 10:17:11.098: E/AndroidRuntime(367): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
06-21 10:17:11.098: E/AndroidRuntime(367): at android.app.ActivityThread.access$2300(ActivityThread.java:125)
06-21 10:17:11.098: E/AndroidRuntime(367): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
06-21 10:17:11.098: E/AndroidRuntime(367): at android.os.Handler.dispatchMessage(Handler.java:99)
06-21 10:17:11.098: E/AndroidRuntime(367): at android.os.Looper.loop(Looper.java:123)
06-21 10:17:11.098: E/AndroidRuntime(367): at android.app.ActivityThread.main(ActivityThread.java:4627)
06-21 10:17:11.098: E/AndroidRuntime(367): at java.lang.reflect.Method.invokeNative(Native Method)
06-21 10:17:11.098: E/AndroidRuntime(367): at java.lang.reflect.Method.invoke(Method.java:521)
06-21 10:17:11.098: E/AndroidRuntime(367): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
06-21 10:17:11.098: E/AndroidRuntime(367): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
06-21 10:17:11.098: E/AndroidRuntime(367): at dalvik.system.NativeStart.main(Native Method)
手动导入umeng包，再运行还是报这个错误，怎么解决？？

**Comment by caoyi01** [comment]
没有截图啊！！！

**Comment by KennethYo** [comment]
properties ——》java build path——》Order and Export 

youzicong

发件人： 涩狼
发送时间： 2013-06-21 12:41
收件人： eoecn/android-app
抄送： KennethYo
主题： Re: [android-app] 运行报NoClassDefFoundError (#79)
没有截图啊！！！

**Comment by caoyi01** [comment]
可以了，谢谢！什么原因啊？

------------------ 原始邮件 ------------------
发件人: "KennethYo"notifications@github.com;
发送时间: 2013年6月21日(星期五) 中午1:01
收件人: "eoecn/android-app"android-app@noreply.github.com; 
抄送: "曹义"282502139@qq.com; 
主题: Re: [android-app] 运行报NoClassDefFoundError (#79)

 properties ——》java build path——》Order and Export  

 youzicong 

 发件人： 涩狼 
 发送时间： 2013-06-21 12:41 
 收件人： eoecn/android-app 
 抄送： KennethYo 
 主题： Re: [android-app] 运行报NoClassDefFoundError (#79) 
 没有截图啊！！！

**Comment by vinceyuan** [comment]
我也遇到了这个问题。
解决方法：
1. 在项目上点右键，Properties -> Java Build Path -> Libraries -> Add JARs... 选中libs目录中的umeng_sdk.jar
2. 然后在同一页面的Order and Export中，勾选umeng_sdk.jar，点击OK。
这样umeng_sdk.jar才被加入了程序包中安装到机器或虚拟机上。

eoe能不能有点专业精神啊，既然都开源了，应该写个步骤教教像我这样的新手设置一下环境，好歹能运行起来啊。我这个新手摸索了半天，才找到方法。不敢独享，赶快发上来，防止别人又浪费时间。

虽然这个umeng_sdk的问题解决了，但还是有另外一个严重的问题导致代码无法运行 https://github.com/eoecn/android-app/issues/78 

我觉得挺奇怪的，这个项目比较活跃，一直有人提交代码，难道他们都没有这些问题吗？

**Comment by feicien** [comment]
sdk升级到22后，很多以前的项目都会出现这样的问题。

**Comment by blessworld** [comment]
@vinceyuan 果然能跑了，非常感谢啊～！

**Comment by mjkohoh** [comment]
这和 #78 是相同的问题吧

**Comment by mjkohoh** [comment]
不顺便关了这个issue @IceskYsl 。原谅我的强迫症

**Comment by mjkohoh** [comment]
要不顺便关了这个issue @IceskYsl 。原谅我的强迫症
